version: '3'
services:
  swagger:
    container_name: schaedel_api_docs
    build:
      context: .
    image: themenschaedel-api-docs:local
    ports:
      - '${SWAGGER_PORT:-8080}:8080'
    volumes:
      - ./api.yaml:/mnt/api.yaml

